# Generated by Django 3.0.5 on 2021-02-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='age',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='active',
        ),
    ]
